## Tutorial 1: Reading a Dpw File using the DataPotentialWell Module

>> Charlie Duke  
Physics Department, Grinnell College   
October 2020

The code in this tutorial will be used in all subsequent tutorials 
that use wavefunctions and/or stationary-state energies read from 
the DataPotentialWell module in the QuantumWell/src folder.

You can copy this notebook to any folder of your choice provided you 
also copy the getPath.py and the dpw data files to that folder.  I'm 
assuming that you executed the config script as described in the 
QuantumWell/README file.  Otherwise, the getPath.py script will not 
have sufficient information to add the path to the QuantumWell/src 
folder.

The code in this notebook illustrates:  
*  Adding the path to QuantumWell/src to sys.path 
*  Creating an instance of the DataPotentialWell class
*  Showing the document string for this class and its methods
*  Reading an example dpw file and using a few of the DataPotentailWell methods   

Use the tab key with cursor following dpw1. to see the list of attributes and methods of the DataPotentialWell class. You can select a method from the list with your cursor. Place your cursor
on dpw1 and do a shift-tab to see the doc string of the 
dpw1 class.

> $dpw1.<tab>$

Use shift-tab to see the doc string and public methods for the class
> $dpw1$ shift-tab with cursor on or after dpw1

You can similarly see the doc string for a specific method  
> $dpw1.method<shift-tab>$

In [1]:
%pylab inline
import sys,os

# if you edit modules loaded in this code, you will have to restart 
# the kernel unless you include the following two lines 
%load_ext autoreload
%autoreload 2

Populating the interactive namespace from numpy and matplotlib


In [2]:
# We have to add the path to the src folder to sys.path
# as in all our tutorials

from getPath import setPath
setPath(sys.path)

# check out sys.path if you want
# The first element should be the path to the src directory
if True:
    print(sys.path)


['/Users/charlesduke/Github/QuantumWell/src', '/Users/charlesduke/Github/QuantumWell/Tutorials', '/Users/charlesduke/Github/root/lib', '/Users/charlesduke/opt/anaconda3/lib/python38.zip', '/Users/charlesduke/opt/anaconda3/lib/python3.8', '/Users/charlesduke/opt/anaconda3/lib/python3.8/lib-dynload', '', '/Users/charlesduke/opt/anaconda3/lib/python3.8/site-packages', '/Users/charlesduke/opt/anaconda3/lib/python3.8/site-packages/aeosa', '/Users/charlesduke/opt/anaconda3/lib/python3.8/site-packages/IPython/extensions', '/Users/charlesduke/.ipython']


In [3]:
# python will look for the DataPotentialWell module in the 
# folders shown in sys.path
from DataPotentialWell import *

In [4]:
# Create an instance of DataPotentialWell 
dpw1 = DataPotentialWell()

In [5]:
# read your dpw file 
filename = 'psi1.dpw'
dpw1.readDpwFile(filename)

# Use the DataPotentialWell class methods to access the well data. 
# For example
xArray = dpw1.getXArray()
vArray = dpw1.getVArray()
psiArray = dpw1.getPsiArray()
print('array shapes ',xArray.shape,' ',psiArray.shape, vArray.shape)
print('first and last values from xArray',xArray[0], xArray[-1])

array shapes  (500,)   (500,) (500,)
first and last values from xArray 0.0 0.4


In [7]:
# can print well data to the screen (but not the large arrays)
dpw1.printData()

    -- DataPotentialWell::printData
       xmin, xmax, xlow, xhigh  0.0 0.4 -0.08000000000000002 0.48000000000000004
       numX,  len(xMinMax), len(xMinHigh)  500 0 0
       binW,   0.0008016032064128256
       wellWidth, wellHeightLeft, wellHeightRight  0.4 inf inf
       vmax set in Plotter, fractRt, fractLf  0.0 0.2 0.2
       k2  26.246843534526526
       AddedVCt  1
       AddedVDict  {1: 1}
       AddedV array 
[0.   0.18 0.   0.   0.  ]
[ 0.18  0.22 40.    0.    0.  ]
[0.22 0.4  0.   0.   0.  ]
         table of stationary states
           1 6.935564600702201
           2 9.626514993545921
           3 28.486030332066957
           4 38.46726970118015
psiArray.shape  (500, 4)
self.statStateNumber  1
self.psiEnergy  6.935564600702201


In [ ]:
# make an inline plot of psi vs x
plt.plot(xArray,psiArray,'.')
plt.grid()

In [ ]:
# try out additional dpw1 methods
# this will get list of methods and all doc strings.
#help(dpw1)


In [9]:
IndexWellEdges = dpw1.getXArrayIndexWellEdges()

In [10]:
IndexWellEdges

array([  0, 499])

In [ ]:
low = 0
high = 499
print(len(xArray))
for i in np.arange(low,high):
    print(xArray[i],vArray[i])
    

In [6]:
#help(dpw1)

In [13]:
v = dpw1.getPotentialList()

In [16]:
v



array([[ 0.  ,  0.18,  0.  ,  0.  ,  0.  ],
       [ 0.18,  0.22, 40.  ,  0.  ,  0.  ],
       [ 0.22,  0.4 ,  0.  ,  0.  ,  0.  ]])

In [17]:
v[:,1]


array([0.18, 0.22, 0.4 ])

In [42]:
x = 0.1
if (x > 0.0) & (x < 0.4):
    ind, = (np.where( x < v[:,1] ))
    indx = ind[0]
else:
    indx = -1
    
print(indx)

0


In [7]:
from SolvePotentialWell import SolvePotentialWell

In [8]:
sw = SolvePotentialWell(dpw1)

In [10]:
sw.getV(0.2)

40.0